# Generated by Django 6.1.1 on 2026-09-23 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('slug', models.SlugField(help_text='Pasta de imagens em static/images/produtos/<slug>/', max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Slug deve conter apenas letras minúsculas, números e hífens.', regex='^[a-z0-9\\-]+$')])),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('Unico', 'Único')], max_length=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Tamanho do produto',
                'verbose_name_plural': 'Tamanhos dos produtos',
                'ordering': ['produto', 'tamanho'],
                'unique_together': {('produto', 'tamanho')},
            },
        ),
    ]
