# Generated by Django 6.1.1 on 2026-10-07 16:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='galeria_no_banco',
            field=models.BooleanField(default=False, help_text='Quando marcado, a galeria vem do banco, mesmo vazia.'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(help_text='Identificador da galeria de imagens.', max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Slug deve conter apenas letras minúsculas, números e hífens.', regex='^[a-z0-9\\-]+$')]),
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('sufixo', models.CharField(max_length=8)),
                ('conteudo', models.BinaryField()),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens do produto',
                'ordering': ['ordem'],
                'unique_together': {('produto', 'ordem')},
            },
        ),
    ]
