# Generated by Django 6.1.1 on 2026-10-05 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64, unique=True)),
                ('copia_e_cola', models.TextField()),
                ('qr_code_base64', models.TextField(blank=True)),
                ('expira_em', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando pagamento'), ('PAGO', 'Pago'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_pix', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Cobrança PIX',
                'verbose_name_plural': 'Cobranças PIX',
                'ordering': ['-criado_em'],
            },
        ),
    ]
